# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sifra.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SifraGUI(object):
    def setupUi(self, SifraGUI):
        SifraGUI.setObjectName("SifraGUI")
        SifraGUI.resize(1125, 879)
        self.centralwidget = QtWidgets.QWidget(SifraGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Bhavya Anand/Downloads/7kmF.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 740, 93, 28))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(860, 740, 211, 28))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 55, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 30, 201, 61))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none'\n"
"color:white'\n"
        "font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(850, 20, 201, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
        "border-radius:none'\n"
        "color:white'\n"
        "font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        SifraGUI.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(SifraGUI)
        QtCore.QMetaObject.connectSlotsByName(SifraGUI)

    def retranslateUi(self, SifraGUI):
        _translate = QtCore.QCoreApplication.translate
        SifraGUI.setWindowTitle(_translate("SifraGUI", "MainWindow"))
        self.pushButton.setText(_translate("SifraGUI", "RUN"))
        self.pushButton_2.setText(_translate("SifraGUI", "TERMINATE"))
        self.label_2.setText(_translate("SifraGUI", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SifraGUI = QtWidgets.QMainWindow()
    ui = Ui_SifraGUI()
    ui.setupUi(SifraGUI)
    SifraGUI.show()
    sys.exit(app.exec_())
